### PR TITLE
Fix crash due to race condition in APCScheduledTask+AddOn

### PR DESCRIPTION
**Pull request by ghost**
Goal: Prevent very low frequency crash after completing Daily Survey.

Summary: Add lock on self in APCScheduledTask to prevent concurrent set() by core data and get() on background thread.

Detail:
In APCScheduledTask+AddOn, self.results has dynamically created accessor methods as this class is a category on an NSManagedObject subclass.  
After completing the Daily Survey, lastResult() is called by APCTasksReminderManager on a background thread to update reminders while self.results is potentially being modified on the main thread by core data to update APCActivitiesViewController. lastResult() is the only method in this class to access self.results.

Ideally we would protect accessors of self.results but since this is a dynamically created property, this can't be done without changing and versioning the data model. Protecting self with synchronized will lock self until core data has updated self.results, then the background thread can access the lastResult of self.results.

apcscheduledtask_racecondition

### CODE REVIEW

**Comment by jwe-apple** [comment]
APCTasksReminderManager looks to be using the main context (a main thread context) heavily on a background thread. Is what it's doing actually expensive? Is there a good reason it can't run on the main runloop?

**Comment by ghost** [comment]
@jwe-apple APCTasksReminderManager's createReminder method is called more frequently than I would like, mostly because of the way the scheduler currently works (which we're currently revising), and to cover all the cases when reminders need updating (e.g.: setReminderOn, setReminderTime). It also relies on results from fetch requests. If/when it's called fewer times, I'd be happy with it running on the main thread.

**Comment by jwe-apple** [comment]
In that case, I think you'll need to avoid using the main thread context on the background thread.

**Comment by ghost** [comment]
@jwe-apple. We're using a background thread to update the reminders using the objects returned from a fetch request run on the main context. The reason we're using the main context is that APCScheduler in updateScheduledTasks() updates the schedules on a secondary context. I want the latest data from the merged contexts when I run my fetch request in APCTasksReminderManager.

**Comment by jwe-apple** [comment]
@chrisinsfo You can't use the main context on a background thread. 
See "Use Thread Confinement to Support Concurrency":
https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/CoreData/Articles/cdConcurrency.html

**Comment by ghost** [comment]
@jwe-apple Latest commit runs fetch request on main thread.

**Comment by jwe-apple** [comment]
But these just fetch managed objects, don't they? You can't use or access properties of these objects outside the main thread either, because they could cause a fault which would require use of the context and the underlying persistent store. The context's cache is not thread-safe.

**Comment by ghost** [comment]
Closing this. We'll put this on the main thread.

**Pull request closed without merging**
