### PR TITLE
Improve APCSignUpPermissionsType for use from Swift

### PR DESCRIPTION
**Pull request by p2**
Resolves ResearchKit/AppKit#21

### CODE REVIEW

**Comment by peculiar** [comment]
Changes look good to me.

**Comment by rsanchezsaez** [comment]
Shouldn't the enumerator element names drop the `k` prefix as well?

`APCSignUpPermissionsTypeNone` instead of `kAPCSignUpPermissionsTypeNone`, etc.

**Comment by p2** [comment]
@rsanchezsaez I'd have preferred that as well, but it doesn't matter for Swift. Since all other enums use the `k` as well and I didn't need to change those I left it in place for `APCSignUpPermissionsType` as well.

**Comment by peculiar** [comment]
The only advantage of the "k" is it helps distinguish an enumeration from a class name.

**Comment by jwe-apple** [comment]
It's uncommon in modern Apple enumerations, although still present especially in the C frameworks.

**Pull request merged**
