### PR TITLE
Fix for the consent date being nil.

### PR DESCRIPTION
**Pull request by insha**
Now checking if the -signatureDateFormatString method returned a nil, and if so using the NSDateFormatterShortStyle for the date. Doing so ensures that the date formatter is not using a nil format; which is why the consent date was being set to nil.

P.S. Pardon the typo in the commit message. It should should be 'date' not 'data'.

### CODE REVIEW

**Comment by jwe-apple** [comment]
r=me

**Comment by jwe-apple** [comment]
Well... Why are you not just using the startDate or endDate timestamps on the consent signature result? You shouldn't need to use the formatted date string.

**Comment by jwe-apple** [comment]
@insha I'm expecting either an update to this patch, or a comment why not. Thanks!

**Comment by insha** [comment]
@jwe-apple Apologize for the delay. I will update the pull request momentarily.

The reason I am not using the 'startDate' or 'endDate' from the consent signature result, is that neither 'startDate' not 'endDate' are obvious choices for accessing consent date, whereas 'signatureDate' on the consent result's signature object seem more appropriate, that is why it was being used.

**Comment by jwe-apple** [comment]
r=me

**Pull request merged**
